[package]
name = "Gruenspan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
ariadne = "0.4.1"
chumsky = "0.8.0"
logos = "0.14.0"
paste = "1.0.15"
